[package]
edition = "2021"
name = "dbf_to_sql"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rusqlite = {version = "0.31.0", features = ["bundled"]}
shapefile = {version = "0.6.0"}
